---
- hosts: mywebserver
  become: yes
  vars:
   myvar1: git
   myvar2: tree
   myvar3: weget
  tasks: 
       - name: i want to display value of the variable  
         debug:
           msg: "{{myvar1}}"