---
- hosts: 172.31.44.125  
  become: yes
  tasks: 
      - name: i wnat to install apache2 on ubuntu
        apt:
          name: apache2
          state: present
      
      - name: i wnat to replace apache2 template with my jinja template
        template:
           src: myindex.j2
           dest: /var/www/html/index.html